name = "UnionCollections"
uuid = "ea2a18ed-132b-4398-a457-2ce4804e5c00"
authors = ["Alexander Plavin <alexander@plav.in>"]
version = "0.1.3"

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"

[weakdeps]
Dictionaries = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4"
FlexiMaps = "6394faf6-06db-4fa8-b750-35ccc60383f7"

[extensions]
DictionariesExt = "Dictionaries"
FlexiMapsDictionariesExt = ["FlexiMaps", "Dictionaries"]
FlexiMapsExt = "FlexiMaps"

[compat]
Accessors = "0.1.32"
Dictionaries = "0.3.25"
FlexiMaps = "0.1.18"
julia = "1.9"
